language: r
cache: packages

r_build_args: --no-build-vignettes
r_check_args: --no-vignettes

notifications:
  email:
    on_success: change
    on_failure: change

services:
    - xvfb
    
before_install:
    - export DISPLAY=:99.0

apt_packages:
    - libssl-dev 
    - libftgl2 
    - libglu1-mesa-dev 
    - libftgl2 
    - libfreetype6-dev  
    - libxml2-dev